[graph]
all-features = true

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []

[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Zlib",
]
exceptions = [
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
# Certain crates that we don't want multiple versions of in the dependency tree
deny = [
    { name = "ahash", deny-multiple-versions = true },
    { name = "android-activity", deny-multiple-versions = true },
    { name = "glam", deny-multiple-versions = true },
    { name = "raw-window-handle", deny-multiple-versions = true },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []